name: Cleanup Workflow Runs
on: 
  push:
    branches: [ "delete_workflow" ]
  workflow_dispatch:

# REMOVE IF THE TOKEN YOU ARE USING ALREADY HAS THESE PERMISSIONS
permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          save_period: '00:00:01'
          save_min_runs_number: 0
          dry: true
