# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy coverage report to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Pages
        uses: actions/configure-pages@v5
 
      - name: Generate HTML reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
        with:
          reports: 'report/jtest/unit/coverage.xml-cobertura.xml'
          targetdir: './coverage-report'
          reporttypes: Html
 
      - name: Add unique path using GitHub Run ID
        run: |
          UNIQUE_PATH="coverage-report-${{ github.run_id }}"  # 使用 GitHub Run ID 生成唯一路径
          mkdir -p ./$UNIQUE_PATH  # 创建路径目录
          mv ./coverage-report/* ./$UNIQUE_PATH/  # 移动生成的HTML报告
          echo "UNIQUE_PATH=$UNIQUE_PATH" >> $GITHUB_ENV  # 存储为环境变量
        shell: bash
 
      - name: Upload artifact and deploy to unique path
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./${{ env.UNIQUE_PATH }}
 
      - name: Deploy to GitHub Pages with unique path
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./${{ env.UNIQUE_PATH }}
          target-path: "/${{ github.run_id }}"  # 使用 GitHub Run ID 作为目标路径
