# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate HTML reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
        with:
          reports: './report/small/coverage-cobertura.xml'
          targetdir: 'D:\test-project\GitHubPagesReport/coverage-report-${{ github.run_id }}'
          reporttypes: Html
          sourcedirs: 'D:\test-project\GitHubPagesReport/coverage-report-${{ github.run_id }}\sources'
          historydir: 'D:\test-project\GitHubPagesReport/coverage-report-${{ github.run_id }}\history'
