# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy local coverage report to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  upload:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate HTML reports
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
        with:
          reports: './report/jtest/unit/coverage-cobertura.xml'
          targetdir: './coverage-report'
          reporttypes: Html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }} # Artifact name        
          path: .\coverage-report # Directory containing files to upload

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [upload] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts  # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: ./coverage-report-${{ github.run_id }}

      - name: Upload artifact and deploy to unique path
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./coverage-report-${{ github.run_id }}
 
      - name: Deploy to GitHub Pages with unique path
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./coverage-report-${{ github.run_id }}
          target-path: "/${{ github.run_id }}"  # 使用 GitHub Run ID 作为目标路径
