  # Sample workflow for building and deploying a Jekyll site to GitHub Pages
  name: Test generate table
  on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  permissions:
    checks: write
    contents: write

  jobs:
    # Build job
    build:
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Generate table
          uses: jchen-parasoft/coverage-report-action@cobertura
          with: 
            path: ./coverage-cobertura.xml

        - name: Upload table file
          uses: actions/upload-artifact@v4
          with:
            name: report-table.md # Artifact name        
            path: ./report-table.md
