on:
  pull_request:
    types: [opened]
    branches:
      - action_deploy
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jchen-parasoft/coverage-report-action@main
        with:
          path: ./coverage-cobertura.xml
          minimum_coverage: 20
