  # Sample workflow for building and deploying a Jekyll site to GitHub Pages
  name: Test generate table
  on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  permissions:
    contents: write
    pages: write
    id-token: write

  # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
  # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
  concurrency:
    group: "pages"

  jobs:
    # Build job
    build:
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Generate table
          uses: jchen-parasoft/coverage-report-action@main
          with: 
            repoToken: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload table file
          uses: actions/upload-artifact@v4
          with:
            name: report-table.md # Artifact name        
            path: .\report-table.md
